### ISSUE TITLE
Rename repository to docker-rstudio or gh-docker-rstudio?

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/docker-rstudio#11]
The main contribution of this repository is to provide a portable and reproducible development environment for R and Python users using Docker. Rename the repository to `docker-rstudio` could contribute to make this contribution more evident.

Another contribution is the integration of GitHub and the use of CI/CD workflow to test and publish notebooks. Hence an alternative name for this repository could be `gh-docker-rstudio`.

@Aryllen @kelshmo Thoughts?

**Comment by kelshmo** [comment]
I don't think it is necessary to call out "gh" in the name of the repository as it is not inherently evident that it means it includes a CI/CD workflow.

**Comment by Aryllen** [comment]
Agreed with @kelshmo on not needing "gh".

docker-rstudio is general and can mean a lot. If you want to emphasize the notebook, collaboration, or other aspect, then it might be good to add on a piece for clarification:
- notebook emphasis: docker-rstudio-notebooks, docker-rstudio-nb, docker-rstudio-rmd
- collaboration emphasis: docker-rstudio-collab
- python: docker-rstudio-py
- python + notebooks: docker-rstudio-python-nb

I think the name really depends on what you want your emphasis to be on. I do agree with adding 'docker-' to the front.

**Comment by tschaffter** [comment]
@kelshmo @Aryllen I'll set the name of the GH repository to `docker-rstudio`. While I like to use the same name for the GH and Docker Hub repository, we will keep using the DH name `sagebionetworks/rstudio`.
